Repository jpadilla/pyjwt, pull requests merged in 2018-03, with the labels that each got.

#334 Add missing links to changelog
  CHANGELOG.md
Labels: docs

#335 Expose InvalidSignatureError on jwt module
  jwt/__init__.py
Labels: bug

#336 Fix bug if application does not specify audience
  AUTHORS
  CHANGELOG.md
  jwt/api_jwt.py
  tests/test_api_jwt.py
Labels: bug

#337 Update legacy instructions for using pycrypto
  docs/installation.rst
Labels: docs

#340 all exceptions inherit from PyJwtError
  jwt/__init__.py
  jwt/exceptions.py
Labels: enhancement
